version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    reviewers:
      - 'ericArbour'
    allow:
      # typeorm
      - dependency-name: 'typeorm'
      - dependency-name: '@nestjs/typeorm'
      - dependency-name: 'pg'
      # nestjs additions
      - dependency-name: '@nestjs/mapped-types'
      - dependency-name: 'class-transformer'
      - dependency-name: 'class-validator'
      # tailwind
      - dependency-name: 'tailwindcss'
      - dependency-name: 'postcss'
      - dependency-name: 'autoprefixer'
      # react
      - dependency-name: 'react-query'
      - dependency-name: 'react-hook-form'
      - dependency-name: '@hookform/resolvers'
      - dependency-name: 'react-select'
