### Create a new ingredient
POST http://localhost:3333/api/ingredients
content-type: application/json

{
  "name": "Gin",
  "categoryId": 1
}

### Find all ingredients
GET http://localhost:3333/api/ingredients

### Find one ingredient by id
GET http://localhost:3333/api/ingredients/5

### Update an ingredient
PATCH http://localhost:3333/api/ingredients/5
content-type: application/json

{
  "name": "Vodka"
}

### Delete an Ingredient
DELETE http://localhost:3333/api/ingredients/5