### Create a new drink
POST http://localhost:3333/api/drinks
content-type: application/json

{
  "name": "Dirty Martini 2",
  "url": "https://www.liquor.com/recipes/dirty-martini/3",
  "glass": { "id": 1 },
  "drinkIngredients": [
    {
      "ingredient": { "id": 1 },
      "amount": 2.5,
      "unit": { "id": 1 }
    },
    {
      "id": null,
      "ingredient": { "id": 2 },
      "amount": 4,
      "unit": { "id": 1 }
    }
  ]
}

### Find all drinks
GET http://localhost:3333/api/drinks

### Find one drink by id
GET http://localhost:3333/api/drinks/1

### Update a drink
PATCH http://localhost:3333/api/drinks/1
content-type: application/json

{
  "name": "Dirty Martini",
  "url": "https://www.liquor.com/recipes/dirty-martini/",
  "glassId": 1,
}

### Delete a drink
DELETE http://localhost:3333/api/drinks/1