### Create a new ingredient type
POST http://localhost:3333/api/ingredient-types
content-type: application/json

{
  "name": "Other"
}

### Find all ingredient types
GET http://localhost:3333/api/ingredient-types

### Find one ingredient type by id
GET http://localhost:3333/api/ingredient-types/1

### Update an ingredient type
PATCH http://localhost:3333/api/ingredient-types/1
content-type: application/json

{
  "name": "Liqueur"
}

### Delete an ingredient type
DELETE http://localhost:3333/api/ingredient-types/1