### Create a new unit
POST http://localhost:3333/api/units
content-type: application/json

{
  "name": "tsp"
}

### Find all units
GET http://localhost:3333/api/units

### Find one unit by id
GET http://localhost:3333/api/units/2

### Update a unit
PATCH http://localhost:3333/api/units/1
content-type: application/json

{
  "name": "Garnish"
}

### Delete a unit
DELETE http://localhost:3333/api/units/1